vulnerable/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<pk>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create/', views.create, name='create' ),
    path('login/', views.login, name='login'),
    path('login_action/', views.loginAction, name='login_action'),
    path('signup/', views.signup, name='signup'),
    path('signup_action/', views.signupAction, name='signup_action'),
    path('logout/', views.logout, name='logout'),
    path('users/<int:pk>/', views.userPage, name='userpage'),
    path('delete_poll/', views.deletePoll, name='delete_poll')

]

vulnerable/vulnerable/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

vulnerable/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
# import for security fix:
# from passlib.hash import bcrypt

class Users(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)

    def set_password(self, pss):
        # Does not use a cryptographic and safe hash function,
        # thus succumbing to a cryptographic failure.
        # SHOULD BE:
        # self.password = bcrypt.hash(pss)
        # INSTEAD OF
        self.password = hash(pss)
        # end (continues below)

    def check_password(self, pss):
        # Previous cryptographic failure continues:
        # SHULD BE: 
        # if bcrypt.verify(pss, self.password):
        # INSTEAD OF
        if int(self.password) == hash(pss):
        # end
            return True
        return False

    def __str__(self) -> str:
        return self.username
    
class Question(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self) -> str:
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self) -> str:
        return self.choice_text

vulnerable/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice, Users

# import for security fix:
# import re

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


def create(request):
    question = request.POST['question']
    user = Users.objects.get(pk=request.session['user'])
    q = user.question_set.create(question_text=question, pub_date=timezone.now())
    q.save()
    q.choice_set.create(choice_text=request.POST['choice_1'], votes=0)
    if request.POST['choice_2']:
        q.choice_set.create(choice_text=request.POST['choice_2'], votes=0)
    if request.POST['choice_3']:
        q.choice_set.create(choice_text=request.POST['choice_3'], votes=0)
    
    return HttpResponseRedirect(reverse('polls:detail', args=(q.id,)))

def results(request, pk):
    # This allows sql injection, which is obviously an injection hazard.
    # SHOULD BE:
    # question = Question.objects.get(pk=pk)
    # INSTEAD OF:
    question = Question.objects.raw('SELECT * FROM polls_question WHERE id ='+pk)[0]
    # end
    print(question)

    return render(request,
                  'polls/results.html',
                  {'question':question})

def login(request):
    return render(request, 'polls/login.html')

def logout(request):
    try:
        del request.session['user']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('polls:index'))

def loginAction(request):
    username = request.POST['username']
    passw = request.POST['password']
    try:
        user = Users.objects.get(username=username)
    except Users.DoesNotExist:
        return render(request,
            'polls/login.html',
            {'error_message':'User not found'})
    if user.check_password(passw):
        request.session['user'] = user.id
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request,
            'polls/login.html',
            {'error_message':'Wrong credentials'})

def signup(request):
    return render(request, 'polls/signup.html')

def signupAction(request):
    username = request.POST['username']
    passw = request.POST['password']
    # Allowing to use weak passwords is an authentication failure.
    # SHOULD INCLUDE:
    # strong_passw = "^(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-.()]).{8,}$"
    # if not re.match(strong_passw, passw):
    #     return render(request,
    #         'polls/signup.html',
    #         {'error_message':'Password is not strong enough. It should be at least 8 symbols long'
    #          ' and contain at least one upper-case, special, and numeric character.'})
    # if re.search(username, passw):
    #     return render(request,
    #          'polls/signup.html',
    #          {'error_message':'Please don\'t include your username in your password.'})
    try:
        user = Users.objects.get(username=username)
        return render(request,
            'polls/signup.html',
            {'error_message':'Username is taken'})
    except Users.DoesNotExist:
        user = Users(username=username)
        user.set_password(passw)
        user.save()
        request.session['user'] = user.id
        return HttpResponseRedirect(reverse('polls:index'))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def userPage(request, pk):
    # this doesn't check the session, and thus allows unathorized access
    # by url manipulation, which is a Broken Access Control flaw.
    # SHOULD INCLUDE:
    # if request.session['user'] != pk:
    #    raise PermissionDenied()

    user = Users.objects.get(pk=pk)
    polls = Question.objects.filter(user=pk)

    return render(request, 'polls/userpage.html', 
                  {'user':user.username,'polls':polls})

def deletePoll(request):
    poll_id = request.POST['to_delete_id']
    poll = Question.objects.get(pk=poll_id)

    if not (poll.user_id == int(request.session['user'])):
        raise PermissionDenied()
    poll.delete()
    return HttpResponseRedirect(reverse('polls:index'))

vulnerable/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

<a href="{% url 'polls:results' question.id %}">Results</a>

vulnerable/polls/templates/polls/index.html
<h1>Poll app</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<br>
{% if request.session.user %}
    <a href="{% url 'polls:logout' %}">Log out</a>
    <br>
    <a href="{% url 'polls:userpage' request.session.user %}">Your page</a>
    <h3>Create new poll:</h3>

    <form action="{% url 'polls:create' %}" method="post">
        {% csrf_token %}
        Question:
        <br>
        <input type="text" name="question" required>
        <br>
        Answer choices (can leave empty):
        <br>
        <input type="text" name="choice_1" required>
        <br>
        <input type="text" name="choice_2">
        <br>
        <input type="text" name="choice_3">
        <br>
        <input type="submit" value="Submit">
    </form>
{% else %}
    <br>
    <a href="{% url 'polls:login' %}">Log in</a>
    <br>
    <a href="{% url 'polls:signup' %}">Sign up</a>
{% endif %}

vulnerable/polls/templates/polls/login.html
<h1>Log in to poll app</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:login_action' %}" method="post">
    {% csrf_token %}
    Username: <br>
    <input type="text" name="username" required>
    <br> Password: <br>
    <input type="password" name="password" required>
    <input type="submit" value="Login">
</form>

vulnerable/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br>
<br>

{% if request.session.user == question.user_id %}
You're the poll creator and can delete the poll.
<form action="{% url 'polls:delete_poll' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="to_delete_id" value="{{ question.id }}">
    <input type="submit" value="delete">
</form>
{% endif %}

vulnerable/polls/templates/polls/signup.html
<h1>Sign up</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:signup_action' %}" method="post">
    {% csrf_token %}
    Username: <br>
    <input type="text" name="username" required>
    <br> Password: <br>
    <input type="password" name="password" required>
    <input type="submit" value="Sign up">
</form>

vulnerable/polls/templates/polls/userpage.html
<h1>This is a private, user-specific page</h1>
<p>You shouldn't see this if you're not {{user}} </p>
<h4>Your polls</h4>
<ul>
    {% for p in polls %}
        <li> <a href="{% url 'polls:detail' p.id %}">{{p.question_text}}</a> </li>
    {% endfor %}
</ul>